### Récupérer tous les status
GET http://localhost:3001/api/status



### Créer un status
POST http://localhost:3001/api/status
Content-Type : application/json

{
    "id" : 3,
  "label": "Inconnu" 
}


### Créer un status avec un label incorrect (pas une string)
POST http://localhost:3001/api/status
Content-Type : application/json

{
  "label": 5 
}


### Créer un status avec un label incorrecte
POST http://localhost:3001/api/status
Content-Type : application/json

{
    "id" : 4,
  "label": 4 
}