### Récupérer tous les repos Rep
GET http://localhost:3001/api/repos

### Récupérer un repo
GET http://localhost:3001/api/repos/R_kgDOMxIC4w

### Récupérer un repo inexistant
GET http://localhost:3001/api/repos/R_XXXXXXXXXX




### Créer un repo
POST http://localhost:3001/api/repos
Content-Type : application/json

{
    "id": "HH",
    "name": "test 2  Repo H",
    "url": "http://New repo test",
    "isPrivate": 1,
    "langIds" : [1, 2, 3, 4]
  }


### Créer un repo avec donnée invalide
POST http://localhost:3001/api/repos
Content-Type : application/json

{
    "id": "K",
    "name": "Repo invalide",
    "url": "repo invalide test",
    "isPrivate": 2,
    "langIds" : [ 2, 3, 4, 5]

  
}



### Modifier un repo
PUT http://localhost:3001/api/repos/BBBBBBBBBB
Content-Type : application/json

{
    "id": "DDDDDDDDDDDD",
    "name": "second  Repo",
    "url": "http://New repo test",
    "isPrivate": 2,
    "languages" : ["JS", "TypeScript", "React"]
  }



###  Supprimer un repo à partir de son id
DELETE http://localhost:3001/api/repos/BBBBBBBBBB