### Récupérer tous les repos
GET http://localhost:3001/api/repos

### Récupérer un repo
GET http://localhost:3001/api/repos/R_kgDOMxIC4w

### Créer un repo
POST http://localhost:3001/api/repos
Content-Type : application/json

{
    "id": "BBBBBBBBBB",
    "name": "new Repo",
    "url": "http://New repo test",
    "isPrivate": 2
  }


### Créer un repo avec donnée invalide
POST http://localhost:3001/api/repos
Content-Type : application/json

{
    "id": "DDDDDDDDDDDD",
    "name": "Repo invalide",
    "url": "http://repo invalide test",
    "isPrivate": 10
  }